
services:
  discourse-app:
    container_name: discourse-app
    image: docker.io/nfrastack/discourse:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.discourse-example-com.rule=Host(`discourse.example.com`)
      - traefik.http.services.discourse-example-com.loadbalancer.server.port=3000
    volumes:
      - ./logs:/logs
      - ./data/uploads:/data/uploads
      - ./data/backups:/data/backups
      - ./data/plugins:/data/plugins
    ports:
      - 3000:3000
    environment:
      - TIMEZONE=America/Vancouver

      - ENABLE_NGINX=FALSE

      - DB_HOST=discourse-db
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password

      - REDIS_HOST=discourse-redis

      - ADMIN_EMAIL=admin@example.com
      - ADMIN_NAME=Admin User
      - ADMIN_USER=admin
      - ADMIN_PASS=min10charpass

      - SITE_HOSTNAME=discourse.example.com
      - DELIVER_SECURE_ASSETS=TRUE

      - SMTP_FROM=noreply@example.com
      - SMTP_TLS=false
      - SMTP_DISABLE_STARTTLS=true
      - SMTP_PORT=25
      - SMTP_HOST=postfix-relay

      #- ENABLE_DB_MIGRATE=FALSE
      #- ENABLE_PRECOMPILE_ASSETS=FALSE
      - DEVELOPER_EMAILS=hostmaster@example.com
    restart: always
    networks:
      - proxy
      - services

  discourse-db:
    container_name: discourse-db
    image: docker.io/nfrastack/postgres:18
    volumes:
      - ./db:/data
    environment:
      - TIMEZONE=America/Vancouver
      - SUPERUSER_PASS=superuser
      - DB_NAME=discourse
      - DB_USER=discourse
      - DB_PASS=password
    restart: always
    networks:
      - services

  discourse-redis:
    image: docker.io/nfrastack/redis:8
    container_name: discourse-redis
    environment:
      - TIMEZONE=America/Vancouver
    restart: always
    networks:
      - services

  discourse-db-backup:
    image: docker.io/tiredofit/db-backup
    container_name: discourse-db-backup
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=discourse-db-backup
      - DB01_HOST=discourse-db
      - DB01_TYPE=postgres
      - DB01_NAME=discourse
      - DB01_USER=discourse
      - DB01_PASS=password
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    restart: always
    networks:
      - services

networks:
  proxy:
    external: true
  services:
    external: true

